language: node_js
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libavahi-compat-libdnssd-dev libasound2-dev
node_js:
  - stable
  - 7
  - 6
  - 5
  - 4
  - 3
  - 2
  - 1
  - 0.12
cache:
  directories:
    - node_modules
